### ISSUE TITLE
去掉进度展示

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/jekyllcn#130]
根据 #129 讨论，决定去掉进度展示。具体需要做以下修改：

1. 给每一篇文档添加一个 frontmatter `update_date`，依照 `README.md` 中的更新日期设置它的值，没有的话置空，至于如何使用 `update_date`，此任务不涉及
2. 去掉 `README.md` 中的「项目进度」模块，但是保留「基础建设」模块
3. 注释掉顶部进度条相关的代码（方便以后添加公告）

**Comment by TimoTokki** [comment]
也可以在 `_config.yml` 里设置默认值：
```
defaults:
  -
    scope:
      path: ""
    values: 
      layout: posts
      update_date: 年 - 月 - 日

```
