### ISSUE TITLE
css 样式问题

### ISSUE THREAD

**Issue by chaucerling** [xcatliu/jekyllcn#74]
举例里的 [table](http://jekyllcn.com/docs/permalinks/#section-2) 超出了宽度
浏览器：chrome 43.0, Firefox 38.0
系统： linux mint 17.1

**Comment by chaucerling** [comment]
[原因](https://github.com/xcatliu/jekyllcn/blob/master/site/_sass/_style.scss#L630)
解决办法：
``` scss
code {
  white-space: normal;
  word-break: break-all;
  ...
}
```
