### ISSUE TITLE
"配置"页面中，"头信息默认值"项中有一个单词错误。

### ISSUE THREAD

**Issue by xavierskip** [xcatliu/jekyllcn#85]
url [http://jekyllcn.com/docs/configuration/#section-4](http://jekyllcn.com/docs/configuration/#section-4)

```
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages" # 以前的 `[post]`<[page]， 在 Jekyll 2.2 里。
    values:
      layout: "project" # 覆盖之前的默认布局
      author: "Mr. Hyde"
```

post替换掉
